version: '3.9'

services:
  api:
    build:
      context: .
      target: prod
    container_name: nest-prod
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres-prod
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prod_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
